model_name_or_path: /home/Qwen3/Qwen3-4B
trust_remote_code: true 
### method 
stage: sft 
do_train: true 
finetuning_type: lora 
lora_rank: 8
lora_target: all
### dataset 
dataset: dy_ReMeDi_qwen3_80b
dataset_dir: /home/llamafactory/data
template: qwen3 
cutoff_len: 4096 
max_samples: 100000000 
overwrite_cache: true 
preprocessing_num_workers: 16 
dataloader_num_workers: 4 
### output 
output_dir:  /home/llamafactory/output_models_Qwen3_4B_ReMeDi_80b_labeled
logging_steps: 5 
save_steps: 100
plot_loss: true 
overwrite_output_dir: true 
save_only_model: false 
report_to: none
### train 
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0 
lr_scheduler_type: cosine 
warmup_ratio: 0.1 
bf16: true
ddp_timeout: 180000000
### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100